### ISSUE TITLE
Subpage Editing Permissions cleared when non-Administrator updates top level page

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#689] opened 2022-07-01 11:17 UTC
ISSUE: Custom role can't see subpages after editing parent page

STEP TO REPLICATE:

1. Edit roles
2. Set it to edit limited page (Check picture)
![image](https://user-images.githubusercontent.com/83811723/176884451-8d235adf-4407-4363-9ae2-9b377c718a6f.png)

3. Log in to the custom role
4. Create a new page
5. Set the parent to "Project A" // _the page that we selected_
6. Save and publish
7. Edit the parent page "Project A"
8. Save, go back to WordPress
9. Observe the issue, the subpage that we just created disappears.

EXPECTED BEHAVIOR: We can still see the subpage that we created even after edit the parent page

**Comment by agapetry** [comment] 2022-07-05 20:03
@rizaardiyanto1412 It sounds like your new page is defaulting to a different parent page before your parent selection and save. Try also assigning a "Set as Parent" permission limited to the same page(s) as your Edit permission.

**Comment by rizaardiyanto1412** [comment] 2022-07-07 11:17
@agapetry Thanks for checking. I tried to add "Set as Parent" permission limited to the same page, and the child page still disappeared upon editing the parent page

**Comment by lemoneyeweb** [comment] 2022-07-23 11:45
Seeing the same issue.

Wordpress users (contributors) each have a parent page with child pages to look after. All works fine until the parent page is edited and saved. After this, the child pages lose their permissions and the user is locked out from editing them.

![image](https://user-images.githubusercontent.com/102378189/180603510-6dc4ef07-a2b7-48af-8739-d40a8df1b90e.png)

So I would say this looks like a confirmed bug.

**Comment by lemoneyeweb** [comment] 2022-07-23 11:46
If you click on the fix sub page permissions, that resolves the issue, but it would be a real pain for an admin to have to fix these permissions after every edit.

**Comment by lemoneyeweb** [comment] 2022-07-25 16:27
Is there generally a time period that these issues get attended to within? Unfortunately, this particular bug is currently making the use of the plugin untenable for our project. If it can't be rectified quickly, we will be forced to find another solution, which is a real shame.

**Comment by lemoneyeweb** [comment] 2022-07-25 16:28
@agapetry - perhaps you couls switch this back to being a confirmed bug?

**Comment by stevejburge** [comment] 2022-07-25 17:45
@lemoneyeweb Thanks for reporting this. We do our best with these bug reports.

Pro members at PublishPress can expect guaranteed reply times. Github issues get our best effort.

**Comment by lemoneyeweb** [comment] 2022-07-26 10:21
Morning @stevejburge - thanks for the reply. I understand your policy with regards Pro members, naturally. However, I'd be very reluctant to suggest to my client that they go Pro with an unresolved bug that effectively means we can't use the plugin, because every time an editor edits their main page their permissions break. A bit of a catch 22.

**Comment by agapetry** [comment] 2022-08-03 20:37
@lemoneyeweb The PR I just merged into development should stop those subpage editing permissions from being cleared.

**Comment by lemoneyeweb** [comment] 2022-08-04 08:33
@agapetry That's great - thank you for the update.

**Closed** 2022-08-17 19:09 UTC
Labels: confirmed bug, php 8
